[buildPlans.iosevka-ori-sans]
family = "Iosevka Ori Sans"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

  [buildPlans.iosevka-ori-sans.variants]
  inherits = "ss15"

    [buildPlans.iosevka-ori-sans.variants.design]
    capital-i = "short-serifed"
    capital-q = "crossing"
    capital-r = "standing-open-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-z = "curly-serifless-with-crossbar"
    f = "flat-hook-tailed"
    g = "single-storey-serifless"
    i = "tailed-serifed"
    l = "zshaped"
    r = "hookless-serifless"
    t = "bent-hook-asymmetric-short-neck2"
    w = "straight-vertical-sides-serifless"
    y = "straight-turn-serifless"
    zero = "slashed"
    one = "base-flat-top-serif"
    three = "two-arcs"
    seven = "curly-serifless"
    nine = "straight-bar"
    paren = "flat-arc"
    brace = "curly"
    at = "threefold"
    dollar = "through"
    bar = "force-upright"
    lig-neq = "slightly-slanted-dotted"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.iosevka-ori-sans.variants.italic]
    capital-i = "short-serifed"
    capital-q = "crossing"
    capital-r = "standing-open-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-z = "curly-serifless-with-crossbar"
    f = "diagonal-tailed"
    g = "double-storey-open"
    i = "tailed-serifed"
    l = "tailed-serifed"
    t = "bent-hook-asymmetric-short-neck2"
    w = "straight-vertical-sides-serifless"
    y = "cursive-serifless"
    zero = "slashed"
    one = "base-flat-top-serif"
    three = "two-arcs"
    seven = "curly-serifless"
    nine = "straight-bar"
    at = "threefold"
    dollar = "through"
    lig-neq = "vertical-dotted"

  [buildPlans.iosevka-ori-sans.ligations]
  inherits = "javascript"

[buildPlans.iosevka-ori-sans.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-ori-sans.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-ori-sans.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-ori-sans.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-ori-sans.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
