[buildPlans.IosevkaOriSans]
family = "Iosevka Ori Sans"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaOriSans.variants]
  inherits = "ss15"

    [buildPlans.IosevkaOriSans.variants.design]
    capital-i = "serifed"
    capital-k = "straight-serifless"
    capital-q = "crossing"
    capital-r = "standing-open-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-z = "curly-serifless"
    a = "single-storey-tailed"
    e = "flat-crossbar"
    f = "extended"
    g = "single-storey-serifless"
    i = "tailed-serifed"
    j = "serifed"
    k = "straight-bottom-right-serifed"
    l = "tailed-serifed"
    r = "serifless"
    t = "bent-hook-short-neck2"
    w = "straight-flat-top-serifless"
    x = "straight-serifless"
    y = "straight-turn-serifless"
    zero = "slashed"
    one = "base-flat-top-serif"
    three = "two-arcs"
    seven = "curly-serifless"
    nine = "straight-bar"
    paren = "flat-arc"
    brace = "curly"
    number-sign = "upright-open"
    at = "threefold-solid-inner"
    dollar = "through-cap"
    percent = "rings-continuous-slash-also-connected"
    bar = "force-upright"
    question = "smooth"
    lig-ltgteq = "slanted"
    lig-neq = "vertical-dotted"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaOriSans.variants.italic]
    capital-i = "serifed"
    capital-k = "straight-serifless"
    capital-q = "crossing"
    capital-r = "standing-open-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-z = "curly-serifless"
    a = "single-storey-serifed"
    b = "toothed-serifless"
    d = "toothed-bottom-serifed"
    e = "rounded"
    f = "extended"
    g = "single-storey-serifless"
    h = "tailed-serifless"
    i = "tailed-serifed"
    j = "serifed"
    k = "cursive-top-left-serifed"
    l = "tailed-serifed"
    m = "tailed-serifless"
    n = "tailed-serifless"
    r = "hookless-serifless"
    t = "bent-hook-short-neck2"
    u = "toothed-bottom-right-serifed"
    v = "straight-serifless"
    w = "straight-flat-top-serifless"
    x = "semi-chancery-straight"
    y = "straight-turn-serifless"
    z = "curly-serifless"
    zero = "slashed"
    one = "base-flat-top-serif"
    three = "two-arcs"
    six = "straight-bar"
    seven = "curly-serifless"
    nine = "straight-bar"
    paren = "flat-arc"
    brace = "curly"
    number-sign = "upright-open"
    at = "threefold-solid-inner"
    dollar = "through-cap"
    percent = "rings-continuous-slash-also-connected"
    bar = "force-upright"
    question = "smooth"
    lig-ltgteq = "slanted"
    lig-neq = "vertical-dotted"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaOriSans.ligations]
  inherits = "javascript"

[buildPlans.IosevkaOriSans.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaOriSans.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaOriSans.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaOriSans.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaOriSans.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"